### PR TITLE
[WIP] Port Plasma-Mobile version to kirigami

### PR DESCRIPTION
**Pull request by JBBgameich**
I haven't finished my work yet, but I decided to open the pull request. This changes do mostly what the title says, but I also changed a few other things.
Please feel free to edit important things on my fork repo.

grafik

TODO:
* [x] port basic funtionality to kirigami
* [x] figure out best page stack options 
* [ ] stop video playback on leaving playerPageComponent
* [x] update youtube user agent string
* [x] remove unneeded margins and borders

### CODE REVIEW

**Comment by llelectronics** [comment]
Very nice work :) 
Will check in more details in the next week as I am currently ill and if everything is OK merge it.

**Comment by JBBgameich** [comment]
Thank you! Take your time :), I'm still looking for optimizations and will work further.

**Comment by JBBgameich** [comment]
Do you prefer a special coding style? I normally use tabs instead of spaces, but now I used spaces because most lines used spaces before, would it be ok for you if I convert everything to tabs?

**Comment by llelectronics** [comment]
I used spaces as this seems to be the default of qtcreator. 
Use whatever is best for you.

**Comment by JBBgameich** [comment]
ok, then I would prefer tabs. Other question: I can't really build with cmake, the executable I get don't works. I get the error "QQmlComponent: Component is not ready". This happens in your original version and with my changes. I only tested using qmlscene for now, but I gues it would be better to copile it really before merging. Could this be related to my OS? The precompiled version from neon.plasma-mobile.org:8080 works by the way.

**Comment by JBBgameich** [comment]
Oh, I would have wanted squash that before merging. 2nd thing: the built binary does not seem to work, at least for me, Does it work on your distro?

**Comment by llelectronics** [comment]
I only took a look at the code as I did not have time to test it. If it does not work I can always revert that merge and you tell me when it's ready then.

**Comment by JBBgameich** [comment]
Ok! Bushan Shah will test building when he updates the package, and as long as probably nobody uses this upstream repo, it's save enough if I tell you tommorrow or later if it worked.

**Pull request merged**
